baseURL: "/"
languageCode: "en-us"
title: "da.wg"
theme: "PaperMod"
publishDir: docs

enableGitInfo: true
relativeURLS: true
googleAnalytics: UA-186134234-1

params: 
    env: production
    defaultTheme: dark
    ShowShareButtons: true

    homeInfoParams:
        Title: hey there!
        Content: welcome to a blog about crypto, trading and coding

    profileMode:
        enabled: false
        title: "<Title>" # optional default will be site title
        imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "archive/"
            - name: Blog
              url: "posts/"


    socialIcons: # optional
        - name: "Twitter"
          url: "https://twitter.com/dawgCapital"

menu:
    main:
        - identifier: categories
          name: categories
          url: "categories/"
          weight: 10
        - identifier: series
          name: series
          url: "series/"
          weight: 20
        - identifier: archive
          name: archive
          url: "archive/"
          weight: 40

taxonomies:
    category: "categories"
    series: "series"

# for search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


