baseurl: "da-wg.github.io/myBlog"
languageCode: "en-us"
title: "da.wg"
theme: "PaperMod"
publishDir: docs

params: 
    defaultTheme: light
    ShowShareButtons: true

    homeInfoParams:
        Title: hey there!
        Content: welcome to a blog about crypto, trading and coding

    profileMode:
        enabled: false
        title: "<Title>" # optional default will be site title
        imageUrl: "<image link>" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Blog
              url: "/posts/"


    socialIcons: # optional
        - name: "Twitter"
          url: "https://twitter.com/dawgCapital"

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: example
          name: example.org
          url: https://example.org
          weight: 30
        - identifier: archive
          name: archive
          url: /archive/
          weight: 40
        - identifier: search
          name: search
          url: /search/
          weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
